### ISSUE TITLE
Add help menu to display keymap, license and source link ?

### ISSUE THREAD

**Issue by NomadeLampe** [RohitAwate/Everest#10]

**Comment by RohitAwate** [comment]
I've purposefully postponed the addition of the menu bar for the very later stages so that I'll be able to properly organize the options. Once that's done, the stuff you mentioned will all be properly integrated into proper menus in the menu bar.

For now, you'll have to refer the README for reference. In the coming weeks, I'll properly start documenting the features in the wiki.
