### ISSUE TITLE
Custom request methods

### ISSUE THREAD

**Issue by heruan** [RohitAwate/Everest#12]
It is legit to use custom HTTP methods, i.e. other than `GET`, `POST`, etc. so it would be great to be able to specify also a custom method for the request.

**Comment by RohitAwate** [comment]
Yes, that is planned and will be coming later. I'll also be adding more of the standard methods (`HEAD`, `OPTIONS`, etc). My plan is to get the rest of the features (authentication, syntax highlighting, etc) up and running with the most common methods in place, so that Everest works in most cases.

Closing this, stay tuned for future updates.
Thanks for reaching out! 👍
